import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const fontInter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${fontInter.variable}`}>
      <body>{children}</body>
    </html>
  )
}
